global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']

  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:3000']

  - job_name: 'golang-app'
    static_configs:
      - targets: ['golang-app:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
